language: cpp

# Prep tools
before_install:
 - sudo apt-get install -y python-serial

# Install tools
install:
# Use prebuilt toolchain:
 - tar -zxvf tools/esp-open-sdk.tar.gz
 - export PATH=$PATH:$PWD/esp-open-sdk/sdk:$PWD/esp-open-sdk/xtensa-lx106-elf/bin

# Run the Build script
script:
 - make all
 - cd bin/
 - ls -la
